# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 14fe4f2c8db99253d85c117cc240eeb9c4f09d4336333955741ed770022a63445c0e8bd537bb41fd7a7f9f82045c20c3b5d4f921ed5a3ce8c1bbe3bacfc13275

test:
  secret_key_base: 0ff7689e10f22b5a363f33fb8aae0a62717f13678c8d20c6cd3e8619ea9cfea1ee2535b939534acc7bd340ffc6d1680c401b8fc57059088bda8ccbdf9240d8c0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
